[package]
name = "terrain-generation"
version = "1.8.0"
authors = ["Barthélemy Paléologue"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.83"
console_error_panic_hook = { version = "0.1.7", optional = true }
float_eq = "1.0.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
image = "0.24.5"
rand = "0.8.5"
chrono = "0.4.23"
gilgamesh = "0.4.0"

[profile.release]
# Tell `rustc` to optimize for speeeed.
opt-level = 3
